name: iOS App Build for Sideloadly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Sjekk ut kildekode
      uses: actions/checkout@v3

    - name: Sett opp Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Installer avhengigheter
      run: flutter pub get

    - name: Bygg usignert iOS app-pakke for ekte iPhone i Debug-modus
      env:
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
      run: flutter build ios --no-codesign --debug

    - name: Konverter til IPA for Sideloadly
      run: |
        mkdir -p Payload
        mv build/ios/iphoneos/Runner.app Payload/
        zip -r ios-release.ipa Payload

    - name: Last opp IPA-fil til GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-release-ipa
        path: ios-release.ipa
